Black border around notification indicator fixed
victor-li/github-white-navbar pull request #5
Opened 2017-02-20 06:47 UTC by anshulsahni

#4 fixed

2017-02-20 20:40 UTC, victor-li commented
Hi @anshulsahni,

Thank you for your contribution!
In the previous version of the GitHub CSS, the following code was used:
```css
.notification-indicator .mail-status {
    ...
    border: 2px solid #f3f3f3;
    ...
}
```

Could you change it into that? Afterwards, I will merge the change.
Thanks! 😄

2017-02-20 21:30 UTC, victor-li requested changes
Hi @anshulsahni,

Thank you for your contribution!
In the previous version of the GitHub CSS, the following code was used:
```css
.notification-indicator .mail-status {
    ...
    border: 2px solid #f3f3f3;
    ...
}
```

Could you change it into that? Afterwards, I will merge the change.
Thanks! 😄

2017-02-20 21:30 UTC, victor-li commented on GitHubWhiteNavBar.user.js
> +    border: none;\
Please change this into `border: 2px solid #f3f3f3;`

2017-02-21 07:46 UTC, anshulsahni commented
@victor-li  fixed
![Uploading Screenshot from 2017-02-21 13-15-34.png…]()

2017-02-21 19:48 UTC, merged

2017-02-21 19:48 UTC, victor-li commented
Thanks @anshulsahni! 😄